### ISSUE TITLE
Working?

### ISSUE THREAD

**Issue by ghost** [AlbertMokrejs/Stuy-AGAR#1]
the game are working?

**Comment by AlbertMokrejs** [comment]
Currently a work in progress. A branch called FINAL will be created once the final version is done.

Currently, there is a stable singleplayer version from which networking will be implemented. 

((This is for a AP Compsci class so the end result will probably not be all that fantastic. But hopefully interesting.))

**Comment by ghost** [comment]
thank you, this game is promising, great work.
